services:
  nfe-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nfe-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start:dev"
    restart: unless-stopped
